spring:
  #?????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/selab-platform
    username: root
    password: abc123
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
